language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=no CXX_COMPILER=/usr/bin/clang++
    - os: linux
      compiler: gcc
      env: DOCKER_BUILD=no CXX_COMPILER=/usr/bin/g++
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=not-yet DISTRO=ubuntu DISTRO_VERSION=14.04
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=not-yet DISTRO=ubuntu DISTRO_VERSION=16.04
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=not-yet DISTRO=ubuntu DISTRO_VERSION=17.04
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=not-yet DISTRO=fedora DISTRO_VERSION=24
    - os: linux
      compiler: clang
      env: DOCKER_BUILD=not-yet DISTRO=fedora DISTRO_VERSION=25

script:
  - if [ "${DOCKER_BUILD?}" = "no" ]; then
      (cd bigtable/api && make -C googleapis OUTPUT=$PWD/googleapis-gens &&
       cmake -DCMAKE_CXX_COMPILER=${CXX_COMPILER} . && make);
    fi
  - if [ "${DOCKER_BUILD?}" = "yes" ]; then
      (cd bigtable/api && docker build -t test-${DISTRO?}-${DISTRO_VERSION?} \
          --build-arg DISTRO_VERSION=${DISTRO_VERSION?}
	  --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}
	  --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
          -f docker/Dockerfile.${DISTRO?} docker/);
    fi

addons:
  apt:
    packages:
      - curl
      - git-core
      - make
      - gcc
      - g++
      - build-essential
      - autoconf
      - automake
      - autoconf-archive
      - libtool
      - pkg-config
      - cmake
      - clang++-3.9

# Cache the grpc directory because building it takes so long ...
cache:
  directories:
    - grpc-build/gcc
    - grpc-build/clang
    - docker-images

install:
  # Make clang++-3.9 available as clang++
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 100
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 100
  - sudo update-alternatives --display clang++ || echo ""
  # If needed clone the grpc directory
  - test -d grpc-build/${CC?}/grpc/.git ||
    git clone https://github.com/grpc/grpc.git grpc-build/${CC?}/grpc
  # needed or not, update the grpc directory ...
  - (cd grpc-build/${CC?}/grpc && git pull && git submodule update --init)
  # build and install in /usr/local
  - (cd grpc-build/${CC?}/grpc && make -j 2 && sudo make install)
  - (cd grpc-build/${CC?}/grpc/third_party/protobuf && sudo make install)

notifications:
  email: false
